services:
  nginx:
    container_name: nginx
    network_mode: host
    image: nginx
    volumes:
    - ./nginx:/etc/nginx/
    ports:
    - "1234:8080"
  postgres:
    container_name: postgres
    network_mode: host
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lol
      POSTGRES_DB: xpong
    ports:
    - "5432:5342"
