version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    networks:
      - trans
    volumes:
      - ./nginx-dev:/etc/nginx/
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    networks:
      - trans
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lol
      POSTGRES_DB: xpong
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
networks:
  trans:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
